### ISSUE TITLE
[Feature] Set hostname, set first user and set root password.

### ISSUE THREAD

**Issue by PedroHLC** [PedroHLC/chaotic-installer-qt#8]
A new screen is required where the user can insert a valid hostname to the new machine, the first user's username, the first user's password, and the root's password.

A double field with matching assertion is desired, but not required. Passwords shouldn't echo. It's recommended to use TextFields and present the input in at least three separate rows.

t's not necessary to create the user, set the password or set/write the hostname, as that will be appended to the setup script so the user can review it on later steps. So only keeping each field in memory is enough.

For layout/design inspirations, one can consult other screens, especially WifiMenu.

Estimated complexity: 100 lines of C code + 130 lines of QML.

Files that may be created:
 * `src/lib/users.hpp`
 * `src/lib/users.cpp`
 * `qml/UserSetup.qml`

Files that have to be modified:
 * `src/main.cpp`: Add include, instantiate new class, connect to a QML property.
 * `qml/MainContainer.qml`: Needs to instantiate the new component and assign an id to it.
 * `chaotic-installer.pro` Add new `cpp` and `hpp` to the build system.

**Comment by vagrantsn** [comment]
Hi @PedroHLC, I noticed there is a `gitignore` for Makefile, which probably prevented it from being pushed:

https://github.com/PedroHLC/chaotic-installer-qt/blob/50b8c5a9541d277562f7bb16f394b20566918a43/.gitignore#L1

Is it possible to contribute without it?

**Comment by PedroHLC** [comment]
Hi @vagnervst, Makefile is actually generated when running `qmake -project ...`. So there's no need for sharing it :smile:

**Comment by vagrantsn** [comment]
@PedroHLC That's odd, it wasn't generated here :thinking: Any idea of what might it be?

**Comment by vagrantsn** [comment]
@PedroHLC I got it working! I had to run `qmake -o Makefile ...` as well, this way the Makefile was generated successfully :slightly_smiling_face: 

I'll try to solve the issue tonight, thanks for your help!

**Comment by vagrantsn** [comment]
@PedroHLC Opened the PR! Drop a review there when possible :smile:
